# Generated by Django 6.1 on 2026-08-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique Node Identifier (e.g., Hostel Block C - Alpha)', max_length=100, unique=True)),
                ('location_area', models.CharField(help_text='Geographical or campus zone (e.g., Campus South Gate)', max_length=150)),
                ('battery_level', models.PositiveIntegerField(default=100, help_text='Solar LiFePO4 battery charge percentage (0-100%)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Operational'), ('MAINTENANCE', 'Scheduled Maintenance'), ('OFFLINE', 'Downtime')], default='ACTIVE', max_length=20)),
                ('signal_quality', models.CharField(choices=[('Optimal', 'Optimal (5.8 GHz - 900 Mbps)'), ('Good', 'Good (5.8 GHz - 650 Mbps)'), ('Fair', 'Fair (2.4 GHz - 300 Mbps)'), ('Weak', 'Weak (Mesh Edge - 100 Mbps)')], default='Optimal', max_length=50)),
                ('uptime_percentage', models.FloatField(default=99.8, help_text='Historical 30-day uptime SLA percentage')),
                ('next_maintenance_date', models.DateTimeField(blank=True, help_text='Next scheduled maintenance or battery servicing window', null=True)),
                ('maintenance_note', models.CharField(blank=True, help_text='Brief engineer note regarding upcoming or current maintenance', max_length=255)),
            ],
            options={
                'verbose_name': 'Mesh Node',
                'verbose_name_plural': 'Mesh Nodes',
                'ordering': ['-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('INSTALL', 'New Node Setup / Antenna Mounting'), ('REALIGN', 'Signal Alignment / Range Boost'), ('REPAIR', 'Solar / Battery / Hardware Servicing')], default='INSTALL', max_length=20)),
                ('address', models.CharField(help_text='Hostel, room number, or street address', max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Technician Review'), ('CONFIRMED', 'Confirmed & Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Specific instructions or issue description for field engineer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, help_text='Associated or nearest mesh node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_schedules', to='core.meshnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Schedule',
                'verbose_name_plural': 'Service Schedules',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='UserDataWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_mb', models.PositiveIntegerField(default=0, help_text='Lifetime perpetual data balance in Megabytes (never expires)')),
                ('wifi_access_key', models.CharField(blank=True, help_text='Unique 8-character uppercase hex PIN for WPA3-Enterprise portal authentication', max_length=16, unique=True)),
                ('assigned_node', models.ForeignKey(blank=True, help_text='Primary connected solar mesh node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_users', to='core.meshnode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data Wallet',
                'verbose_name_plural': 'User Data Wallets',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique voucher code (e.g. ECO-10GB-SUN)', max_length=32, unique=True)),
                ('data_amount_mb', models.PositiveIntegerField(help_text='Data allocation in Megabytes')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Voucher',
                'verbose_name_plural': 'Data Vouchers',
                'ordering': ['-is_redeemed', '-data_amount_mb'],
            },
        ),
    ]
