# Generated by Django 6.1 on 2026-08-25 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service title (e.g. New Node Setup & Antenna Mounting)', max_length=120)),
                ('code', models.CharField(help_text='Unique slug code (e.g. INSTALL, REALIGN)', max_length=30, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what this service covers')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated time in minutes')),
                ('price', models.CharField(default='Free for Campus Students', help_text='Cost or billing terms', max_length=50)),
                ('icon_name', models.CharField(default='wrench', help_text='Lucide icon identifier (wrench, radio, sun, zap, activity, wifi)', max_length=50)),
                ('badge_color', models.CharField(default='emerald', help_text='Tailwind accent color (emerald, teal, cyan, amber, purple)', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Assigned certified field technician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='technician_notes',
            field=models.TextField(blank=True, help_text='Findings, diagnostics, or resolution remarks left by the technician'),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='notes',
            field=models.TextField(blank=True, help_text='Specific instructions or issue description from the student/customer'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='service_type',
            field=models.CharField(choices=[('INSTALL', 'New Node Setup / Antenna Mounting'), ('REALIGN', 'Signal Alignment / Range Boost'), ('SOLAR_REPAIR', 'Solar / Battery Diagnostics'), ('EMERGENCY', 'Emergency Offline Repair'), ('ROUTER_CONFIG', 'Captive Portal / Router Configuration'), ('REPAIR', 'General Hardware Servicing')], default='INSTALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed & Dispatched'), ('IN_PROGRESS', 'In Progress / Onsite'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='service_type_ref',
            field=models.ForeignKey(blank=True, help_text='Optional linked dynamic service category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.servicetype'),
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(help_text='Direct mobile or WhatsApp contact', max_length=30)),
                ('specialization', models.CharField(default='RF Antenna & Solar Diagnostics', help_text='Technical domain expertise', max_length=150)),
                ('assigned_zone', models.CharField(default='Campus Zone / Hostels', help_text='Primary service zone', max_length=150)),
                ('is_available', models.BooleanField(default=True, help_text='Active availability for dispatch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Profile',
                'verbose_name_plural': 'Technician Profiles',
            },
        ),
    ]
